name: basin
dependencies:
  - python>3.5,<3.8
  - pip
  - pyqt
  - pip:
    - numpy>1.14.6,<1.19.4
    - numba>=0.43.1
    - scipy
    - scikit-image
    - torch>=1.6
    - tensorflow>=2.1.0
    - opencv-python-headless
    - pyqtgraph>=0.11.0rc0
    - natsort
    - google-cloud-storage
    - tqdm
    - tifffile